# Setup
name:         A blog in Oka
tagline:      "Blog by Henry Lo, Brady Cooper, and Aziz Asadullah"
baseurl:      "/okaCrisisBlog"
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
